//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vue
{
    using System;
    using System.Collections.Generic;
    
    public partial class etatcolis
    {
        public int Codeetatcolis { get; set; }
        public int Codecolis { get; set; }
        public int Codeetat { get; set; }
        public int Codelivreur { get; set; }
        public string Date { get; set; }
        public string Commentaire { get; set; }
    
        public virtual colis colis { get; set; }
        public virtual Etat Etat { get; set; }
        public virtual livreur livreur { get; set; }
    }
}
