//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vue
{
    using System;
    using System.Collections.Generic;
    
    public partial class livreur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livreur()
        {
            this.etatcolis = new HashSet<etatcolis>();
        }
    
        public int Codelivreur { get; set; }
        public string Nomlivreur { get; set; }
        public string Numtel { get; set; }
        public string Fraislivraison { get; set; }
        public Nullable<int> iddepot { get; set; }
    
        public virtual Depot Depot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etatcolis> etatcolis { get; set; }
    }
}
